- crates/cargo-codspeed/src/app.rs
- crates/cargo-codspeed/src/build.rs
- crates/cargo-codspeed/tests/features.in/.gitignore
- crates/cargo-codspeed/tests/features.in/Cargo.toml
- crates/cargo-codspeed/tests/features.in/benches/bench.rs
- crates/cargo-codspeed/tests/features.rs
- crates/cargo-codspeed/tests/helpers.rs
> feat: support `--features` build flag

- crates/bencher_compat/src/compat.rs
- crates/codspeed/src/codspeed.rs
- crates/criterion_compat/benches/criterion_integration/compare_functions.rs
- crates/criterion_compat/src/compat/bencher.rs
- Recursive
- Recursive[20]
- Recursive[21]
> feat!: add warmup runs 

- .github/workflows/ci.yml
- Cargo.lock
- crates/bencher_compat/benches/bencher_example.rs
- crates/bencher_compat/src/compat.rs
- crates/bencher_compat/src/lib.rs
- crates/cargo-codspeed/src/run.rs
- crates/codspeed/Cargo.toml
- crates/codspeed/src/lib.rs
- crates/codspeed/src/macros.rs
- crates/codspeed/src/utils.rs
- crates/criterion_compat/benches/test_benches.rs
- crates/criterion_compat/src/compat/group.rs
- crates/criterion_compat/src/compat/macros.rs
- crates/criterion_compat/src/lib.rs
- chore(ci): use moon setup rust action
- fix: fix relative git path issue when using working-directory
> fix: fix relative path when using working-directory

- .github/workflows/release.yml
- Cargo.lock
- crates/cargo-codspeed/Cargo.toml
- crates/cargo-codspeed/README.md
I failed to install `cargo-codspeed` locally due to not having openssl installed on system (nix).
```
--- stderr
Package openssl was not found in the pkg-config search path.
Perhaps you should add the directory containing `openssl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'openssl' found
```
This PR adds the `vendored-openssl` feature from `cargo`.
I made sure this got built successfully with `cargo build --release --features vendored-openssl` and then run the built binary against by project.
> feat(cargo-codspeed): add `--features vendored-openssl`

- crates/cargo-codspeed/src/build.rs
`cargo codspeed` is printing with `--verbose`, which fills the log with lots of compilation messages that are uninteresting to normal users. 
e.g. build benchmark step in https://github.com/web-infra-dev/oxc/actions/runs/6095539763/job/16539311128
This PR sets the verbosity to normal.
I ran the built binary on my project and sees no compilation messages.
> chore(cargo-codspeed): set verbosity to normal

- crates/criterion_compat/benches/test_benches.rs
- crates/criterion_compat/src/compat/bencher.rs
> feat(criterion): allow explicit lifetime usage with compat

- crates/criterion_compat/src/compat/criterion.rs
- crates/criterion_compat/src/compat/group.rs
Fix for https://github.com/CodSpeedHQ/codspeed-rust/issues/25
> feat(criterion): `BenchmarkGroup` compat with `Measurement` generic param and `plot_config`

- crates/bencher_compat/README.md
- crates/cargo-codspeed/README.md
- crates/codspeed/README.md
- crates/criterion_compat/README.md
- crates/criterion_compat/benches/test_benches.rs
- crates/criterion_compat/src/compat/group.rs
- chore: add codspeed badges in sub readmes
- fix(criterion): add a default measurement to the benchmark group struct
- feat(criterion): support explicit lifetime for BenchmarkGroup
> fix(criterion): benchmark group generics breaking change

- crates/cargo-codspeed/Cargo.toml
- crates/cargo-codspeed/src/build.rs
- crates/cargo-codspeed/src/prelude.rs
- crates/criterion_compat/src/compat/mod.rs
As pointed out by @Boshen in https://github.com/oxc-project/oxc/pull/2343, we can build all the benches in a single command.
> feat(cargo-codspeed): build all benches in a single cargo build

- .vscode/settings.json
- crates/codspeed/src/utils.rs
Closes https://github.com/CodSpeedHQ/codspeed-rust/issues/35
The problem was that `repo_path` was "canonicalized" but `abs_path` was not, and this broke it because paths on Window get the `\\?\` (UNC I think it's called?) thing added at the begining, this small difference made `strip_prefix` return an error. Now, both paths are "canonicalized" before used.
> fix: Fixed path strip panic on Windows

- crates/cargo-codspeed/src/build.rs
- crates/cargo-codspeed/tests/helpers.rs
- crates/cargo-codspeed/tests/package_in_deps.in/.gitignore
- crates/cargo-codspeed/tests/package_in_deps.in/Cargo.toml
- crates/cargo-codspeed/tests/package_in_deps.in/benches/bencher_example.rs
- crates/cargo-codspeed/tests/package_in_deps.rs
> fix(cargo-codspeed): fix build when package is included in its deps

- Cargo.lock
- crates/bencher_compat/build.rs
- crates/cargo-codspeed/Cargo.toml
- crates/cargo-codspeed/src/app.rs
- crates/cargo-codspeed/src/build.rs
- crates/cargo-codspeed/src/run.rs
- crates/codspeed/Cargo.toml
- crates/criterion_compat/Cargo.toml
- crates/criterion_compat/build.rs
- rust-toolchain.toml
Update the version of dependencies to current versions, and move to Rust
1.80. Currently, the crate cannot be compiled on anything newer than
Rust 1.77 because that's the latest version supported by the previous
cargo dependency. Updating it to a more recent version fixes compile
problems that appear within gix.
Signed-off-by: Moritz Hoffmann <antiguru@gmail.com>
> chore: bump dependency versions and move to Rust 1.80

- .github/workflows/ci.yml
- Cargo.lock
- crates/bencher_compat/Cargo.toml
- crates/bencher_compat/build.rs
- crates/codspeed/Cargo.toml
- crates/criterion_compat/Cargo.toml
- crates/criterion_compat/build.rs
> chore: set MSRV to 1.74 and enforce it in CI

- crates/codspeed/src/request/arch/unsupported.rs
- crates/codspeed/src/request/mod.rs
Fixes build on architecture we don't support instrumentation for yet: https://github.com/astral-sh/ruff/issues/12662
> fix: allow building codspeed-rust on unsupported architectures

- crates/bencher_compat/README.md
- crates/criterion_compat/README.md
Simplify how rust benchmarks are defined by removing the need to install both `criterion` and `codspeed-criterion-compat`, or both `bencher` and `codspeed-bencher-compat`.
> docs: simplify rust benchmarks definition

- .cargo/config.toml
- .vscode/settings.json
- Cargo.lock
- crates/cargo-codspeed/Cargo.toml
- crates/cargo-codspeed/README.md
- crates/cargo-codspeed/build.rs
- crates/cargo-codspeed/src/app.rs
- crates/cargo-codspeed/src/build.rs
- crates/cargo-codspeed/src/helpers.rs
- crates/cargo-codspeed/src/main.rs
- crates/cargo-codspeed/src/prelude.rs
- crates/cargo-codspeed/src/run.rs
- crates/cargo-codspeed/tests/package_in_deps.rs
- crates/cargo-codspeed/tests/simple.rs
- crates/cargo-codspeed/tests/workspace.rs
- crates/criterion_compat/benches/criterion_integration/external_process.rs
Removes usage of cargo lib in favor of the recommended way of using [cargo from cli](https://doc.rust-lang.org/cargo/reference/external-tools.html#custom-subcommands)
> Replace cargo api crate by cargo cli invocations

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .gitmodules
- Cargo.lock
- crates/divan_compat/examples/Cargo.toml
- crates/divan_compat/examples/benches/the_algorithms.rs
- crates/divan_compat/examples/src/lib.rs
- crates/divan_compat/examples/src/the_algorithms/mod.rs
- **feat: implement benchmarks for TheAlgorithms (backtracking, big_interger, bit_manipulation)**
- **chore: DO NOT MERGE test latest runner version**
> feat: add some TheAlgorithm benches

- crates/cargo-codspeed/src/app.rs
- crates/cargo-codspeed/src/build.rs
- crates/cargo-codspeed/tests/features.in/Cargo.toml
- crates/cargo-codspeed/tests/features.in/benches/bench.rs
- crates/cargo-codspeed/tests/features.rs
Added `passthrough_flags` to the `BuildOptions` which can be used to add more flags in the future if needed. 
Closes #57
> feat: add support for all-features and no-default-features

- crates/cargo-codspeed/src/run.rs
Signals can be rewritten to error codes (see: https://stackoverflow.com/a/24104579)
> feat(cargo-codspeed): rethrow exit code

- crates/divan_compat/README.md
> chore(divan_compat): remove consts from unsupported features in README

- crates/cargo-codspeed/src/build.rs
- crates/divan_compat/benches/basic_example.rs
- Root cause was missing debug symbols, because cargo seems to strip them by default if they are not explicitly enabled in `Cargo.toml` and only through rust flags (this is a theory, have not dived into cargo code)
- Noticed that fibo(500) is actually a very huge and overflowing integer when troubleshooting benches without release profile, so fixed it
> Cod 711 file name missing in codspeed rust flamegraph

- Cargo.lock
- crates/cargo-codspeed/Cargo.toml
The current version fails `failed to parse manifest at `/path/to/oxc/bench-javascript-transformer-written-in-rust/Cargo.toml` with 
```toml
[package]
edition = "2024"
```
> chore(cargo-codspeed): bump `cargo_metadata` to v0.19.2

- Cargo.lock
- Cargo.toml
- crates/cargo-codspeed/Cargo.toml
- crates/codspeed/Cargo.toml
- crates/codspeed/src/fifo.rs
- crates/codspeed/src/lib.rs
- crates/codspeed/src/shared.rs
- crates/criterion_compat/criterion_fork/src/analysis/mod.rs
- crates/criterion_compat/criterion_fork/src/bencher.rs
- crates/criterion_compat/criterion_fork/src/routine.rs
- crates/divan_compat/divan_fork/src/bench/mod.rs
- crates/divan_compat/divan_fork/src/divan.rs
- crates/divan_compat/divan_fork/src/thread_pool.rs
> Cod 674 collect profiles while benchmarks are running

- crates/codspeed/src/utils.rs
- crates/codspeed/src/walltime.rs
- crates/criterion_compat/criterion_fork/src/analysis/mod.rs
- crates/criterion_compat/criterion_fork/src/macros.rs
- crates/divan_compat/divan_fork/src/divan.rs
Previous output (different project): 
```
[11:15] not-matthias:perf-walltime-repo (main)> cargo codspeed run                                                                                                                                                                                                      devenv-shell-env
[cargo-codspeed] Measurement mode: Walltime
Collected 1 benchmark suite(s) to run
Running perf-walltime-repo my_benchmark
Timer precision: 24 ns
my_benchmark  fastest       │ slowest       │ median        │ mean          │ samples │ iters
╰─ fibonacci                │               │               │               │         │
╰─ 32      Failed to send benchmark URI to runner: FIFO does not exist: /tmp/runner.ctl.fifo
4.382 ms      │ 11.75 ms      │ 5.129 ms      │ 5.862 ms …
```
> fix: do not display error when sending benchmark uri

- crates/codspeed/src/codspeed.rs
It has been stable for quite a while now.
> chore: use std::hint::black_box

- .github/workflows/ci.yml
> Fix build on windows

- .github/workflows/ci.yml
- crates/codspeed/build.rs
- crates/codspeed/src/instrument_hooks/mod.rs
> fix: build on macos

- .github/workflows/ci.yml
- crates/codspeed/Cargo.toml
- crates/codspeed/build.rs
- crates/codspeed/src/instrument_hooks/mod.rs
CI runners that don't have LIBCLANG pre-installed would fail. We don't support Windows/MacOS for now, so we shouldn't do extra work with bindgen and cc.
This reverts commit 8054636ee6e2e572a8f5fc9ec988474942de5d8f.
Fixes https://github.com/CodSpeedHQ/codspeed-rust/issues/133
> Revert "fix(codspeed): always compile instrument-hooks (with stubs)"
